### PR TITLE
Patch v3.0.1

### PR DESCRIPTION
**Pull request by dosse**
- Fix https://github.com/sdmx-twg/sdmx-ml/issues/36  
- Fix https://github.com/sdmx-twg/sdmx-ml/issues/34  
- Fix https://github.com/sdmx-twg/sdmx-ml/issues/30
- Fix https://github.com/sdmx-twg/sdmx-ml/issues/29

### CODE REVIEW

**Review by jgager — CHANGES_REQUESTED** [review]
Documentation should be updated if the value is no longer repeatable.

**Review by jgager — COMMENTED** [review]
Why is the new MetadataType abstract? If this is intentional, what is the expectation for creating derived types and will the documentation be updated to reflect this?

**Comment by dosse** [comment]
Helllo @jgager, Thank you for the comments. With @stratosn we agree on the incorrect abstract type, as we don't have a derived type. We removed the abstract property. We also corrected the documentation.  
Could you please recheck? If ok for you then Stratos could approve.

**Comment by jgager** [comment]
@dosse looks good.

**Review by stratosn — APPROVED** [review]

**Pull request merged**
