### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dosse**
Adding SDMX-XML 2.1 specifications to generic SDMX-ML repository (before releasing the 3.0.0 specifications)

### CODE REVIEW

**Comment by dosse** [comment]
@sdmx3mdt I just noted that in document SDMX_2-1_SECTION_3A_PART_IV_DATA.doc at the end a section 4 "SPECIAL DATA FUNCTION" was added that has an ambiguous interpretation of the action "Append":

_A dataset with an action of Append is assumed to be an incremental update. This means that one the information provided explicitly in the message should be altered. Any data attribute or observation value that is to be changed must be provided. However, the absence of an observation value or a data attribute at any level does not imply deletion; instead it is simply implied that the value is to remain unchanged. Therefore, it is valid and acceptable to send a data message with an action of Append which contains only a Series elements with attribute values. In this case, the values for the attributes will be updated. Note that it is not permissible to update data attributes using partial keys (outside of those associated with defined groups). In order to update an attribute, a full key must always be provided even if the message format does not require this._

But in 2.1, according to the Information Model document, the actions were:
------------------
_648 • Append
649
650 Data or metadata is an incremental update for an existing data/metadata set or the
651 provision of new data or documentation (attribute values) formerly absent. If any of the
652 supplied data or metadata is already present, it will not replace that data or metadata. This
653 corresponds to the "Update" value found in version 1.0 of the SDMX Technical Standards
654
655 • Replace
656
657 Data/metadata is to be replaced, and may also include additional data/metadata to be
658 appended.
659
660 • Delete
661
662 Data/Metadata is to be deleted.
663
664 • Information
665
666 Data and metadata are for information purposes._

-----------------------

This is not the same behaviour. While I agree that the actions need an urgent revision and work was already started but then excluded from 3.0.0, I don't think that any changes, especially non-agreed ones, should be added to 2.1. 

Is there a great appetite to change the actions now in v3.0.0 and we should again address this?

**Comment by sdmx3mdt** [comment]
> @sdmx3mdt I just noted that in document SDMX_2-1_SECTION_3A_PART_IV_DATA.doc at the end a section 4 "SPECIAL DATA FUNCTION" was added that has an ambiguous interpretation of the action "Append":
> This is not the same behaviour. While I agree that the actions need an urgent revision and work was already started but then excluded from 3.0.0, I don't think that any changes, especially non-agreed ones, should be added to 2.1.
> Is there a great appetite to change the actions now in v3.0.0 and we should again address this?

@dosse I don't believe this implies any appetite to change the v3.0.0 dataset actions. That section on Special Data Functions is unchanged as far as I can see since the original 2011 version of the PART IV document. 
If it's ambiguous, should that chapter in 3A PART IV be removed?
The Section 2 Information Model specification has a clear explanation of the ActionTypes.

**Comment by dosse** [comment]
I see now, this inconsistency is also in the 2.1 documentation on the sdmx.org web site.

**Comment by dosse** [comment]
@sdmx3mdt In the structure document (SDMX_3-0-0_SECTION_3A_PART_III_STRUCTURE.doc), shouldn't **isMultiLingual** have as default "false"?

**Comment by dosse** [comment]
Hello @sosna, @stratosn, @agent96, @egreising, could one of you please approve this request merge so that we have a clean release version with the 2.1 files in this repo before adding the new 3.0.0 files to the develop branch? Thanks in advance.

**Review by stratosn — APPROVED** [review]

**Pull request merged**
