### PR TITLE
fix version to 1.0

### PR DESCRIPTION
**Pull request by agent96**
Categorisation fixed to v1.0 by making version prohibited

### CODE REVIEW

**Review by stratosn — COMMENTED** [review]
one comment, a bit more generic: do we also need to change the targetNamespace to 3_1 ?

**Comment by dosse** [comment]
@agent96 @stratosn Instead of forbidding the version, shouldn't we do like done for AgencyScheme, where the version is fixed to "1.0", if I remember correctly?

**Comment by agent96** [comment]
> @agent96 @stratosn Instead of forbidding the version, shouldn't we do like done for AgencyScheme, where the version is fixed to "1.0", if I remember correctly?

I agree fixed to 1.0 would have been my solution, but I copied the current solution for AgencyScheme which prohibits it:

```
<xs:complexType name="OrganisationSchemeBaseType" abstract="true">
		<xs:annotation>
			<xs:documentation>OrganisationSchemeBaseType is an abstract base type for any organisation scheme.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:restriction base="ItemSchemeType">
				<xs:sequence>
					<xs:element ref="common:Annotations" minOccurs="0"/>
					<xs:element ref="common:Link" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="common:Name" maxOccurs="unbounded"/>
					<xs:element ref="common:Description" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="version" type="common:VersionType" use="prohibited"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

```

**Comment by stratosn** [comment]
Interestingly enough I also remembered that "1.0" was the default, but indeed this was not the case in the previous schemas for Agencies (I do not know if this was by mistake).
It might be safer to go that way, I guess, ie with a default "1.0" version for non-versioned artefacts.

**Comment by dosse** [comment]
Ok!   
I agree then with Stratos. But that's my fault. I should have changed the targetNamespace to 3_1 for all files in the branch. Maybe this could be the last step (another commit)?

**Review by dosse — APPROVED** [review]

**Comment by stratosn** [comment]
@dosse yes, let's make the 3_1 version bump after everything else is merged.

**Pull request merged**
